/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.carbondata.format;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * Compressions for column page supported by CarbonData.
 */
public enum CompressionCodec implements org.apache.thrift.TEnum {
  SNAPPY(0),
  DEPRECATED(1);

  private final int value;

  private CompressionCodec(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CompressionCodec findByValue(int value) { 
    switch (value) {
      case 0:
        return SNAPPY;
      case 1:
        return DEPRECATED;
      default:
        return null;
    }
  }
}
