/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.carbondata.format;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
/**
 * Footer for indexed carbon file for V3 format
 */
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2019-12-05")
public class FileFooter3 implements org.apache.thrift.TBase<FileFooter3, FileFooter3._Fields>, java.io.Serializable, Cloneable, Comparable<FileFooter3> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FileFooter3");

  private static final org.apache.thrift.protocol.TField NUM_ROWS_FIELD_DESC = new org.apache.thrift.protocol.TField("num_rows", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField SEGMENT_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("segment_info", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField BLOCKLET_INDEX_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("blocklet_index_list", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField BLOCKLET_INFO_LIST3_FIELD_DESC = new org.apache.thrift.protocol.TField("blocklet_info_list3", org.apache.thrift.protocol.TType.LIST, (short)4);
  private static final org.apache.thrift.protocol.TField DICTIONARY_FIELD_DESC = new org.apache.thrift.protocol.TField("dictionary", org.apache.thrift.protocol.TType.STRUCT, (short)5);
  private static final org.apache.thrift.protocol.TField IS_SORT_FIELD_DESC = new org.apache.thrift.protocol.TField("is_sort", org.apache.thrift.protocol.TType.BOOL, (short)6);
  private static final org.apache.thrift.protocol.TField EXTRA_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("extra_info", org.apache.thrift.protocol.TType.MAP, (short)7);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new FileFooter3StandardSchemeFactory());
    schemes.put(TupleScheme.class, new FileFooter3TupleSchemeFactory());
  }

  public long num_rows; // required
  public SegmentInfo segment_info; // required
  public List<BlockletIndex> blocklet_index_list; // required
  public List<BlockletInfo3> blocklet_info_list3; // optional
  public org.apache.carbondata.format.ColumnDictionaryChunk dictionary; // optional
  public boolean is_sort; // optional
  public Map<String,String> extra_info; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NUM_ROWS((short)1, "num_rows"),
    SEGMENT_INFO((short)2, "segment_info"),
    BLOCKLET_INDEX_LIST((short)3, "blocklet_index_list"),
    BLOCKLET_INFO_LIST3((short)4, "blocklet_info_list3"),
    DICTIONARY((short)5, "dictionary"),
    IS_SORT((short)6, "is_sort"),
    EXTRA_INFO((short)7, "extra_info");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NUM_ROWS
          return NUM_ROWS;
        case 2: // SEGMENT_INFO
          return SEGMENT_INFO;
        case 3: // BLOCKLET_INDEX_LIST
          return BLOCKLET_INDEX_LIST;
        case 4: // BLOCKLET_INFO_LIST3
          return BLOCKLET_INFO_LIST3;
        case 5: // DICTIONARY
          return DICTIONARY;
        case 6: // IS_SORT
          return IS_SORT;
        case 7: // EXTRA_INFO
          return EXTRA_INFO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __NUM_ROWS_ISSET_ID = 0;
  private static final int __IS_SORT_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.BLOCKLET_INFO_LIST3,_Fields.DICTIONARY,_Fields.IS_SORT,_Fields.EXTRA_INFO};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NUM_ROWS, new org.apache.thrift.meta_data.FieldMetaData("num_rows", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.SEGMENT_INFO, new org.apache.thrift.meta_data.FieldMetaData("segment_info", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, SegmentInfo.class)));
    tmpMap.put(_Fields.BLOCKLET_INDEX_LIST, new org.apache.thrift.meta_data.FieldMetaData("blocklet_index_list", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, BlockletIndex.class))));
    tmpMap.put(_Fields.BLOCKLET_INFO_LIST3, new org.apache.thrift.meta_data.FieldMetaData("blocklet_info_list3", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, BlockletInfo3.class))));
    tmpMap.put(_Fields.DICTIONARY, new org.apache.thrift.meta_data.FieldMetaData("dictionary", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, org.apache.carbondata.format.ColumnDictionaryChunk.class)));
    tmpMap.put(_Fields.IS_SORT, new org.apache.thrift.meta_data.FieldMetaData("is_sort", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.EXTRA_INFO, new org.apache.thrift.meta_data.FieldMetaData("extra_info", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FileFooter3.class, metaDataMap);
  }

  public FileFooter3() {
  }

  public FileFooter3(
    long num_rows,
    SegmentInfo segment_info,
    List<BlockletIndex> blocklet_index_list)
  {
    this();
    this.num_rows = num_rows;
    setNum_rowsIsSet(true);
    this.segment_info = segment_info;
    this.blocklet_index_list = blocklet_index_list;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FileFooter3(FileFooter3 other) {
    __isset_bitfield = other.__isset_bitfield;
    this.num_rows = other.num_rows;
    if (other.isSetSegment_info()) {
      this.segment_info = new SegmentInfo(other.segment_info);
    }
    if (other.isSetBlocklet_index_list()) {
      List<BlockletIndex> __this__blocklet_index_list = new ArrayList<BlockletIndex>(other.blocklet_index_list.size());
      for (BlockletIndex other_element : other.blocklet_index_list) {
        __this__blocklet_index_list.add(new BlockletIndex(other_element));
      }
      this.blocklet_index_list = __this__blocklet_index_list;
    }
    if (other.isSetBlocklet_info_list3()) {
      List<BlockletInfo3> __this__blocklet_info_list3 = new ArrayList<BlockletInfo3>(other.blocklet_info_list3.size());
      for (BlockletInfo3 other_element : other.blocklet_info_list3) {
        __this__blocklet_info_list3.add(new BlockletInfo3(other_element));
      }
      this.blocklet_info_list3 = __this__blocklet_info_list3;
    }
    if (other.isSetDictionary()) {
      this.dictionary = new org.apache.carbondata.format.ColumnDictionaryChunk(other.dictionary);
    }
    this.is_sort = other.is_sort;
    if (other.isSetExtra_info()) {
      Map<String,String> __this__extra_info = new HashMap<String,String>(other.extra_info);
      this.extra_info = __this__extra_info;
    }
  }

  public FileFooter3 deepCopy() {
    return new FileFooter3(this);
  }

  @Override
  public void clear() {
    setNum_rowsIsSet(false);
    this.num_rows = 0;
    this.segment_info = null;
    this.blocklet_index_list = null;
    this.blocklet_info_list3 = null;
    this.dictionary = null;
    setIs_sortIsSet(false);
    this.is_sort = false;
    this.extra_info = null;
  }

  public long getNum_rows() {
    return this.num_rows;
  }

  public FileFooter3 setNum_rows(long num_rows) {
    this.num_rows = num_rows;
    setNum_rowsIsSet(true);
    return this;
  }

  public void unsetNum_rows() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __NUM_ROWS_ISSET_ID);
  }

  /** Returns true if field num_rows is set (has been assigned a value) and false otherwise */
  public boolean isSetNum_rows() {
    return EncodingUtils.testBit(__isset_bitfield, __NUM_ROWS_ISSET_ID);
  }

  public void setNum_rowsIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __NUM_ROWS_ISSET_ID, value);
  }

  public SegmentInfo getSegment_info() {
    return this.segment_info;
  }

  public FileFooter3 setSegment_info(SegmentInfo segment_info) {
    this.segment_info = segment_info;
    return this;
  }

  public void unsetSegment_info() {
    this.segment_info = null;
  }

  /** Returns true if field segment_info is set (has been assigned a value) and false otherwise */
  public boolean isSetSegment_info() {
    return this.segment_info != null;
  }

  public void setSegment_infoIsSet(boolean value) {
    if (!value) {
      this.segment_info = null;
    }
  }

  public int getBlocklet_index_listSize() {
    return (this.blocklet_index_list == null) ? 0 : this.blocklet_index_list.size();
  }

  public java.util.Iterator<BlockletIndex> getBlocklet_index_listIterator() {
    return (this.blocklet_index_list == null) ? null : this.blocklet_index_list.iterator();
  }

  public void addToBlocklet_index_list(BlockletIndex elem) {
    if (this.blocklet_index_list == null) {
      this.blocklet_index_list = new ArrayList<BlockletIndex>();
    }
    this.blocklet_index_list.add(elem);
  }

  public List<BlockletIndex> getBlocklet_index_list() {
    return this.blocklet_index_list;
  }

  public FileFooter3 setBlocklet_index_list(List<BlockletIndex> blocklet_index_list) {
    this.blocklet_index_list = blocklet_index_list;
    return this;
  }

  public void unsetBlocklet_index_list() {
    this.blocklet_index_list = null;
  }

  /** Returns true if field blocklet_index_list is set (has been assigned a value) and false otherwise */
  public boolean isSetBlocklet_index_list() {
    return this.blocklet_index_list != null;
  }

  public void setBlocklet_index_listIsSet(boolean value) {
    if (!value) {
      this.blocklet_index_list = null;
    }
  }

  public int getBlocklet_info_list3Size() {
    return (this.blocklet_info_list3 == null) ? 0 : this.blocklet_info_list3.size();
  }

  public java.util.Iterator<BlockletInfo3> getBlocklet_info_list3Iterator() {
    return (this.blocklet_info_list3 == null) ? null : this.blocklet_info_list3.iterator();
  }

  public void addToBlocklet_info_list3(BlockletInfo3 elem) {
    if (this.blocklet_info_list3 == null) {
      this.blocklet_info_list3 = new ArrayList<BlockletInfo3>();
    }
    this.blocklet_info_list3.add(elem);
  }

  public List<BlockletInfo3> getBlocklet_info_list3() {
    return this.blocklet_info_list3;
  }

  public FileFooter3 setBlocklet_info_list3(List<BlockletInfo3> blocklet_info_list3) {
    this.blocklet_info_list3 = blocklet_info_list3;
    return this;
  }

  public void unsetBlocklet_info_list3() {
    this.blocklet_info_list3 = null;
  }

  /** Returns true if field blocklet_info_list3 is set (has been assigned a value) and false otherwise */
  public boolean isSetBlocklet_info_list3() {
    return this.blocklet_info_list3 != null;
  }

  public void setBlocklet_info_list3IsSet(boolean value) {
    if (!value) {
      this.blocklet_info_list3 = null;
    }
  }

  public org.apache.carbondata.format.ColumnDictionaryChunk getDictionary() {
    return this.dictionary;
  }

  public FileFooter3 setDictionary(org.apache.carbondata.format.ColumnDictionaryChunk dictionary) {
    this.dictionary = dictionary;
    return this;
  }

  public void unsetDictionary() {
    this.dictionary = null;
  }

  /** Returns true if field dictionary is set (has been assigned a value) and false otherwise */
  public boolean isSetDictionary() {
    return this.dictionary != null;
  }

  public void setDictionaryIsSet(boolean value) {
    if (!value) {
      this.dictionary = null;
    }
  }

  public boolean isIs_sort() {
    return this.is_sort;
  }

  public FileFooter3 setIs_sort(boolean is_sort) {
    this.is_sort = is_sort;
    setIs_sortIsSet(true);
    return this;
  }

  public void unsetIs_sort() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __IS_SORT_ISSET_ID);
  }

  /** Returns true if field is_sort is set (has been assigned a value) and false otherwise */
  public boolean isSetIs_sort() {
    return EncodingUtils.testBit(__isset_bitfield, __IS_SORT_ISSET_ID);
  }

  public void setIs_sortIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __IS_SORT_ISSET_ID, value);
  }

  public int getExtra_infoSize() {
    return (this.extra_info == null) ? 0 : this.extra_info.size();
  }

  public void putToExtra_info(String key, String val) {
    if (this.extra_info == null) {
      this.extra_info = new HashMap<String,String>();
    }
    this.extra_info.put(key, val);
  }

  public Map<String,String> getExtra_info() {
    return this.extra_info;
  }

  public FileFooter3 setExtra_info(Map<String,String> extra_info) {
    this.extra_info = extra_info;
    return this;
  }

  public void unsetExtra_info() {
    this.extra_info = null;
  }

  /** Returns true if field extra_info is set (has been assigned a value) and false otherwise */
  public boolean isSetExtra_info() {
    return this.extra_info != null;
  }

  public void setExtra_infoIsSet(boolean value) {
    if (!value) {
      this.extra_info = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case NUM_ROWS:
      if (value == null) {
        unsetNum_rows();
      } else {
        setNum_rows((Long)value);
      }
      break;

    case SEGMENT_INFO:
      if (value == null) {
        unsetSegment_info();
      } else {
        setSegment_info((SegmentInfo)value);
      }
      break;

    case BLOCKLET_INDEX_LIST:
      if (value == null) {
        unsetBlocklet_index_list();
      } else {
        setBlocklet_index_list((List<BlockletIndex>)value);
      }
      break;

    case BLOCKLET_INFO_LIST3:
      if (value == null) {
        unsetBlocklet_info_list3();
      } else {
        setBlocklet_info_list3((List<BlockletInfo3>)value);
      }
      break;

    case DICTIONARY:
      if (value == null) {
        unsetDictionary();
      } else {
        setDictionary((org.apache.carbondata.format.ColumnDictionaryChunk)value);
      }
      break;

    case IS_SORT:
      if (value == null) {
        unsetIs_sort();
      } else {
        setIs_sort((Boolean)value);
      }
      break;

    case EXTRA_INFO:
      if (value == null) {
        unsetExtra_info();
      } else {
        setExtra_info((Map<String,String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case NUM_ROWS:
      return getNum_rows();

    case SEGMENT_INFO:
      return getSegment_info();

    case BLOCKLET_INDEX_LIST:
      return getBlocklet_index_list();

    case BLOCKLET_INFO_LIST3:
      return getBlocklet_info_list3();

    case DICTIONARY:
      return getDictionary();

    case IS_SORT:
      return isIs_sort();

    case EXTRA_INFO:
      return getExtra_info();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case NUM_ROWS:
      return isSetNum_rows();
    case SEGMENT_INFO:
      return isSetSegment_info();
    case BLOCKLET_INDEX_LIST:
      return isSetBlocklet_index_list();
    case BLOCKLET_INFO_LIST3:
      return isSetBlocklet_info_list3();
    case DICTIONARY:
      return isSetDictionary();
    case IS_SORT:
      return isSetIs_sort();
    case EXTRA_INFO:
      return isSetExtra_info();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof FileFooter3)
      return this.equals((FileFooter3)that);
    return false;
  }

  public boolean equals(FileFooter3 that) {
    if (that == null)
      return false;

    boolean this_present_num_rows = true;
    boolean that_present_num_rows = true;
    if (this_present_num_rows || that_present_num_rows) {
      if (!(this_present_num_rows && that_present_num_rows))
        return false;
      if (this.num_rows != that.num_rows)
        return false;
    }

    boolean this_present_segment_info = true && this.isSetSegment_info();
    boolean that_present_segment_info = true && that.isSetSegment_info();
    if (this_present_segment_info || that_present_segment_info) {
      if (!(this_present_segment_info && that_present_segment_info))
        return false;
      if (!this.segment_info.equals(that.segment_info))
        return false;
    }

    boolean this_present_blocklet_index_list = true && this.isSetBlocklet_index_list();
    boolean that_present_blocklet_index_list = true && that.isSetBlocklet_index_list();
    if (this_present_blocklet_index_list || that_present_blocklet_index_list) {
      if (!(this_present_blocklet_index_list && that_present_blocklet_index_list))
        return false;
      if (!this.blocklet_index_list.equals(that.blocklet_index_list))
        return false;
    }

    boolean this_present_blocklet_info_list3 = true && this.isSetBlocklet_info_list3();
    boolean that_present_blocklet_info_list3 = true && that.isSetBlocklet_info_list3();
    if (this_present_blocklet_info_list3 || that_present_blocklet_info_list3) {
      if (!(this_present_blocklet_info_list3 && that_present_blocklet_info_list3))
        return false;
      if (!this.blocklet_info_list3.equals(that.blocklet_info_list3))
        return false;
    }

    boolean this_present_dictionary = true && this.isSetDictionary();
    boolean that_present_dictionary = true && that.isSetDictionary();
    if (this_present_dictionary || that_present_dictionary) {
      if (!(this_present_dictionary && that_present_dictionary))
        return false;
      if (!this.dictionary.equals(that.dictionary))
        return false;
    }

    boolean this_present_is_sort = true && this.isSetIs_sort();
    boolean that_present_is_sort = true && that.isSetIs_sort();
    if (this_present_is_sort || that_present_is_sort) {
      if (!(this_present_is_sort && that_present_is_sort))
        return false;
      if (this.is_sort != that.is_sort)
        return false;
    }

    boolean this_present_extra_info = true && this.isSetExtra_info();
    boolean that_present_extra_info = true && that.isSetExtra_info();
    if (this_present_extra_info || that_present_extra_info) {
      if (!(this_present_extra_info && that_present_extra_info))
        return false;
      if (!this.extra_info.equals(that.extra_info))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_num_rows = true;
    list.add(present_num_rows);
    if (present_num_rows)
      list.add(num_rows);

    boolean present_segment_info = true && (isSetSegment_info());
    list.add(present_segment_info);
    if (present_segment_info)
      list.add(segment_info);

    boolean present_blocklet_index_list = true && (isSetBlocklet_index_list());
    list.add(present_blocklet_index_list);
    if (present_blocklet_index_list)
      list.add(blocklet_index_list);

    boolean present_blocklet_info_list3 = true && (isSetBlocklet_info_list3());
    list.add(present_blocklet_info_list3);
    if (present_blocklet_info_list3)
      list.add(blocklet_info_list3);

    boolean present_dictionary = true && (isSetDictionary());
    list.add(present_dictionary);
    if (present_dictionary)
      list.add(dictionary);

    boolean present_is_sort = true && (isSetIs_sort());
    list.add(present_is_sort);
    if (present_is_sort)
      list.add(is_sort);

    boolean present_extra_info = true && (isSetExtra_info());
    list.add(present_extra_info);
    if (present_extra_info)
      list.add(extra_info);

    return list.hashCode();
  }

  @Override
  public int compareTo(FileFooter3 other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetNum_rows()).compareTo(other.isSetNum_rows());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNum_rows()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.num_rows, other.num_rows);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSegment_info()).compareTo(other.isSetSegment_info());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSegment_info()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.segment_info, other.segment_info);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBlocklet_index_list()).compareTo(other.isSetBlocklet_index_list());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBlocklet_index_list()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.blocklet_index_list, other.blocklet_index_list);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBlocklet_info_list3()).compareTo(other.isSetBlocklet_info_list3());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBlocklet_info_list3()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.blocklet_info_list3, other.blocklet_info_list3);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDictionary()).compareTo(other.isSetDictionary());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDictionary()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dictionary, other.dictionary);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIs_sort()).compareTo(other.isSetIs_sort());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIs_sort()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.is_sort, other.is_sort);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetExtra_info()).compareTo(other.isSetExtra_info());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExtra_info()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.extra_info, other.extra_info);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("FileFooter3(");
    boolean first = true;

    sb.append("num_rows:");
    sb.append(this.num_rows);
    first = false;
    if (!first) sb.append(", ");
    sb.append("segment_info:");
    if (this.segment_info == null) {
      sb.append("null");
    } else {
      sb.append(this.segment_info);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("blocklet_index_list:");
    if (this.blocklet_index_list == null) {
      sb.append("null");
    } else {
      sb.append(this.blocklet_index_list);
    }
    first = false;
    if (isSetBlocklet_info_list3()) {
      if (!first) sb.append(", ");
      sb.append("blocklet_info_list3:");
      if (this.blocklet_info_list3 == null) {
        sb.append("null");
      } else {
        sb.append(this.blocklet_info_list3);
      }
      first = false;
    }
    if (isSetDictionary()) {
      if (!first) sb.append(", ");
      sb.append("dictionary:");
      if (this.dictionary == null) {
        sb.append("null");
      } else {
        sb.append(this.dictionary);
      }
      first = false;
    }
    if (isSetIs_sort()) {
      if (!first) sb.append(", ");
      sb.append("is_sort:");
      sb.append(this.is_sort);
      first = false;
    }
    if (isSetExtra_info()) {
      if (!first) sb.append(", ");
      sb.append("extra_info:");
      if (this.extra_info == null) {
        sb.append("null");
      } else {
        sb.append(this.extra_info);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'num_rows' because it's a primitive and you chose the non-beans generator.
    if (segment_info == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'segment_info' was not present! Struct: " + toString());
    }
    if (blocklet_index_list == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'blocklet_index_list' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (segment_info != null) {
      segment_info.validate();
    }
    if (dictionary != null) {
      dictionary.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FileFooter3StandardSchemeFactory implements SchemeFactory {
    public FileFooter3StandardScheme getScheme() {
      return new FileFooter3StandardScheme();
    }
  }

  private static class FileFooter3StandardScheme extends StandardScheme<FileFooter3> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FileFooter3 struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NUM_ROWS
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.num_rows = iprot.readI64();
              struct.setNum_rowsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SEGMENT_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.segment_info = new SegmentInfo();
              struct.segment_info.read(iprot);
              struct.setSegment_infoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // BLOCKLET_INDEX_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list176 = iprot.readListBegin();
                struct.blocklet_index_list = new ArrayList<BlockletIndex>(_list176.size);
                BlockletIndex _elem177;
                for (int _i178 = 0; _i178 < _list176.size; ++_i178)
                {
                  _elem177 = new BlockletIndex();
                  _elem177.read(iprot);
                  struct.blocklet_index_list.add(_elem177);
                }
                iprot.readListEnd();
              }
              struct.setBlocklet_index_listIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // BLOCKLET_INFO_LIST3
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list179 = iprot.readListBegin();
                struct.blocklet_info_list3 = new ArrayList<BlockletInfo3>(_list179.size);
                BlockletInfo3 _elem180;
                for (int _i181 = 0; _i181 < _list179.size; ++_i181)
                {
                  _elem180 = new BlockletInfo3();
                  _elem180.read(iprot);
                  struct.blocklet_info_list3.add(_elem180);
                }
                iprot.readListEnd();
              }
              struct.setBlocklet_info_list3IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // DICTIONARY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.dictionary = new org.apache.carbondata.format.ColumnDictionaryChunk();
              struct.dictionary.read(iprot);
              struct.setDictionaryIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // IS_SORT
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.is_sort = iprot.readBool();
              struct.setIs_sortIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // EXTRA_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map182 = iprot.readMapBegin();
                struct.extra_info = new HashMap<String,String>(2*_map182.size);
                String _key183;
                String _val184;
                for (int _i185 = 0; _i185 < _map182.size; ++_i185)
                {
                  _key183 = iprot.readString();
                  _val184 = iprot.readString();
                  struct.extra_info.put(_key183, _val184);
                }
                iprot.readMapEnd();
              }
              struct.setExtra_infoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetNum_rows()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'num_rows' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FileFooter3 struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(NUM_ROWS_FIELD_DESC);
      oprot.writeI64(struct.num_rows);
      oprot.writeFieldEnd();
      if (struct.segment_info != null) {
        oprot.writeFieldBegin(SEGMENT_INFO_FIELD_DESC);
        struct.segment_info.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.blocklet_index_list != null) {
        oprot.writeFieldBegin(BLOCKLET_INDEX_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.blocklet_index_list.size()));
          for (BlockletIndex _iter186 : struct.blocklet_index_list)
          {
            _iter186.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.blocklet_info_list3 != null) {
        if (struct.isSetBlocklet_info_list3()) {
          oprot.writeFieldBegin(BLOCKLET_INFO_LIST3_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.blocklet_info_list3.size()));
            for (BlockletInfo3 _iter187 : struct.blocklet_info_list3)
            {
              _iter187.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.dictionary != null) {
        if (struct.isSetDictionary()) {
          oprot.writeFieldBegin(DICTIONARY_FIELD_DESC);
          struct.dictionary.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetIs_sort()) {
        oprot.writeFieldBegin(IS_SORT_FIELD_DESC);
        oprot.writeBool(struct.is_sort);
        oprot.writeFieldEnd();
      }
      if (struct.extra_info != null) {
        if (struct.isSetExtra_info()) {
          oprot.writeFieldBegin(EXTRA_INFO_FIELD_DESC);
          {
            oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.extra_info.size()));
            for (Map.Entry<String, String> _iter188 : struct.extra_info.entrySet())
            {
              oprot.writeString(_iter188.getKey());
              oprot.writeString(_iter188.getValue());
            }
            oprot.writeMapEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FileFooter3TupleSchemeFactory implements SchemeFactory {
    public FileFooter3TupleScheme getScheme() {
      return new FileFooter3TupleScheme();
    }
  }

  private static class FileFooter3TupleScheme extends TupleScheme<FileFooter3> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FileFooter3 struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI64(struct.num_rows);
      struct.segment_info.write(oprot);
      {
        oprot.writeI32(struct.blocklet_index_list.size());
        for (BlockletIndex _iter189 : struct.blocklet_index_list)
        {
          _iter189.write(oprot);
        }
      }
      BitSet optionals = new BitSet();
      if (struct.isSetBlocklet_info_list3()) {
        optionals.set(0);
      }
      if (struct.isSetDictionary()) {
        optionals.set(1);
      }
      if (struct.isSetIs_sort()) {
        optionals.set(2);
      }
      if (struct.isSetExtra_info()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetBlocklet_info_list3()) {
        {
          oprot.writeI32(struct.blocklet_info_list3.size());
          for (BlockletInfo3 _iter190 : struct.blocklet_info_list3)
          {
            _iter190.write(oprot);
          }
        }
      }
      if (struct.isSetDictionary()) {
        struct.dictionary.write(oprot);
      }
      if (struct.isSetIs_sort()) {
        oprot.writeBool(struct.is_sort);
      }
      if (struct.isSetExtra_info()) {
        {
          oprot.writeI32(struct.extra_info.size());
          for (Map.Entry<String, String> _iter191 : struct.extra_info.entrySet())
          {
            oprot.writeString(_iter191.getKey());
            oprot.writeString(_iter191.getValue());
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FileFooter3 struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.num_rows = iprot.readI64();
      struct.setNum_rowsIsSet(true);
      struct.segment_info = new SegmentInfo();
      struct.segment_info.read(iprot);
      struct.setSegment_infoIsSet(true);
      {
        org.apache.thrift.protocol.TList _list192 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.blocklet_index_list = new ArrayList<BlockletIndex>(_list192.size);
        BlockletIndex _elem193;
        for (int _i194 = 0; _i194 < _list192.size; ++_i194)
        {
          _elem193 = new BlockletIndex();
          _elem193.read(iprot);
          struct.blocklet_index_list.add(_elem193);
        }
      }
      struct.setBlocklet_index_listIsSet(true);
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list195 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.blocklet_info_list3 = new ArrayList<BlockletInfo3>(_list195.size);
          BlockletInfo3 _elem196;
          for (int _i197 = 0; _i197 < _list195.size; ++_i197)
          {
            _elem196 = new BlockletInfo3();
            _elem196.read(iprot);
            struct.blocklet_info_list3.add(_elem196);
          }
        }
        struct.setBlocklet_info_list3IsSet(true);
      }
      if (incoming.get(1)) {
        struct.dictionary = new org.apache.carbondata.format.ColumnDictionaryChunk();
        struct.dictionary.read(iprot);
        struct.setDictionaryIsSet(true);
      }
      if (incoming.get(2)) {
        struct.is_sort = iprot.readBool();
        struct.setIs_sortIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TMap _map198 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.extra_info = new HashMap<String,String>(2*_map198.size);
          String _key199;
          String _val200;
          for (int _i201 = 0; _i201 < _map198.size; ++_i201)
          {
            _key199 = iprot.readString();
            _val200 = iprot.readString();
            struct.extra_info.put(_key199, _val200);
          }
        }
        struct.setExtra_infoIsSet(true);
      }
    }
  }

}

