/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.carbondata.format;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
/**
 * Merged carbon index file information
 */
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2019-12-05")
public class MergedBlockIndex implements org.apache.thrift.TBase<MergedBlockIndex, MergedBlockIndex._Fields>, java.io.Serializable, Cloneable, Comparable<MergedBlockIndex> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MergedBlockIndex");

  private static final org.apache.thrift.protocol.TField FILE_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("fileData", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MergedBlockIndexStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MergedBlockIndexTupleSchemeFactory());
  }

  public List<ByteBuffer> fileData; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FILE_DATA((short)1, "fileData");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FILE_DATA
          return FILE_DATA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FILE_DATA, new org.apache.thrift.meta_data.FieldMetaData("fileData", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING            , true))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MergedBlockIndex.class, metaDataMap);
  }

  public MergedBlockIndex() {
  }

  public MergedBlockIndex(
    List<ByteBuffer> fileData)
  {
    this();
    this.fileData = fileData;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MergedBlockIndex(MergedBlockIndex other) {
    if (other.isSetFileData()) {
      List<ByteBuffer> __this__fileData = new ArrayList<ByteBuffer>(other.fileData);
      this.fileData = __this__fileData;
    }
  }

  public MergedBlockIndex deepCopy() {
    return new MergedBlockIndex(this);
  }

  @Override
  public void clear() {
    this.fileData = null;
  }

  public int getFileDataSize() {
    return (this.fileData == null) ? 0 : this.fileData.size();
  }

  public java.util.Iterator<ByteBuffer> getFileDataIterator() {
    return (this.fileData == null) ? null : this.fileData.iterator();
  }

  public void addToFileData(ByteBuffer elem) {
    if (this.fileData == null) {
      this.fileData = new ArrayList<ByteBuffer>();
    }
    this.fileData.add(elem);
  }

  public List<ByteBuffer> getFileData() {
    return this.fileData;
  }

  public MergedBlockIndex setFileData(List<ByteBuffer> fileData) {
    this.fileData = fileData;
    return this;
  }

  public void unsetFileData() {
    this.fileData = null;
  }

  /** Returns true if field fileData is set (has been assigned a value) and false otherwise */
  public boolean isSetFileData() {
    return this.fileData != null;
  }

  public void setFileDataIsSet(boolean value) {
    if (!value) {
      this.fileData = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FILE_DATA:
      if (value == null) {
        unsetFileData();
      } else {
        setFileData((List<ByteBuffer>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FILE_DATA:
      return getFileData();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FILE_DATA:
      return isSetFileData();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MergedBlockIndex)
      return this.equals((MergedBlockIndex)that);
    return false;
  }

  public boolean equals(MergedBlockIndex that) {
    if (that == null)
      return false;

    boolean this_present_fileData = true && this.isSetFileData();
    boolean that_present_fileData = true && that.isSetFileData();
    if (this_present_fileData || that_present_fileData) {
      if (!(this_present_fileData && that_present_fileData))
        return false;
      if (!this.fileData.equals(that.fileData))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_fileData = true && (isSetFileData());
    list.add(present_fileData);
    if (present_fileData)
      list.add(fileData);

    return list.hashCode();
  }

  @Override
  public int compareTo(MergedBlockIndex other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetFileData()).compareTo(other.isSetFileData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFileData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fileData, other.fileData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MergedBlockIndex(");
    boolean first = true;

    sb.append("fileData:");
    if (this.fileData == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.fileData, sb);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (fileData == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'fileData' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MergedBlockIndexStandardSchemeFactory implements SchemeFactory {
    public MergedBlockIndexStandardScheme getScheme() {
      return new MergedBlockIndexStandardScheme();
    }
  }

  private static class MergedBlockIndexStandardScheme extends StandardScheme<MergedBlockIndex> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MergedBlockIndex struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FILE_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.fileData = new ArrayList<ByteBuffer>(_list8.size);
                ByteBuffer _elem9;
                for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                {
                  _elem9 = iprot.readBinary();
                  struct.fileData.add(_elem9);
                }
                iprot.readListEnd();
              }
              struct.setFileDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MergedBlockIndex struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.fileData != null) {
        oprot.writeFieldBegin(FILE_DATA_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.fileData.size()));
          for (ByteBuffer _iter11 : struct.fileData)
          {
            oprot.writeBinary(_iter11);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MergedBlockIndexTupleSchemeFactory implements SchemeFactory {
    public MergedBlockIndexTupleScheme getScheme() {
      return new MergedBlockIndexTupleScheme();
    }
  }

  private static class MergedBlockIndexTupleScheme extends TupleScheme<MergedBlockIndex> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MergedBlockIndex struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      {
        oprot.writeI32(struct.fileData.size());
        for (ByteBuffer _iter12 : struct.fileData)
        {
          oprot.writeBinary(_iter12);
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MergedBlockIndex struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
        struct.fileData = new ArrayList<ByteBuffer>(_list13.size);
        ByteBuffer _elem14;
        for (int _i15 = 0; _i15 < _list13.size; ++_i15)
        {
          _elem14 = iprot.readBinary();
          struct.fileData.add(_elem14);
        }
      }
      struct.setFileDataIsSet(true);
    }
  }

}

