/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.carbondata.format;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2019-12-05")
public class ParentColumnTableRelation implements org.apache.thrift.TBase<ParentColumnTableRelation, ParentColumnTableRelation._Fields>, java.io.Serializable, Cloneable, Comparable<ParentColumnTableRelation> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ParentColumnTableRelation");

  private static final org.apache.thrift.protocol.TField RELATION_IDENTIFIER_FIELD_DESC = new org.apache.thrift.protocol.TField("relationIdentifier", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField COLUMN_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("columnId", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField COLUMN_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("columnName", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ParentColumnTableRelationStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ParentColumnTableRelationTupleSchemeFactory());
  }

  public RelationIdentifier relationIdentifier; // required
  public String columnId; // required
  public String columnName; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RELATION_IDENTIFIER((short)1, "relationIdentifier"),
    COLUMN_ID((short)2, "columnId"),
    COLUMN_NAME((short)3, "columnName");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RELATION_IDENTIFIER
          return RELATION_IDENTIFIER;
        case 2: // COLUMN_ID
          return COLUMN_ID;
        case 3: // COLUMN_NAME
          return COLUMN_NAME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RELATION_IDENTIFIER, new org.apache.thrift.meta_data.FieldMetaData("relationIdentifier", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, RelationIdentifier.class)));
    tmpMap.put(_Fields.COLUMN_ID, new org.apache.thrift.meta_data.FieldMetaData("columnId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.COLUMN_NAME, new org.apache.thrift.meta_data.FieldMetaData("columnName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ParentColumnTableRelation.class, metaDataMap);
  }

  public ParentColumnTableRelation() {
  }

  public ParentColumnTableRelation(
    RelationIdentifier relationIdentifier,
    String columnId,
    String columnName)
  {
    this();
    this.relationIdentifier = relationIdentifier;
    this.columnId = columnId;
    this.columnName = columnName;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ParentColumnTableRelation(ParentColumnTableRelation other) {
    if (other.isSetRelationIdentifier()) {
      this.relationIdentifier = new RelationIdentifier(other.relationIdentifier);
    }
    if (other.isSetColumnId()) {
      this.columnId = other.columnId;
    }
    if (other.isSetColumnName()) {
      this.columnName = other.columnName;
    }
  }

  public ParentColumnTableRelation deepCopy() {
    return new ParentColumnTableRelation(this);
  }

  @Override
  public void clear() {
    this.relationIdentifier = null;
    this.columnId = null;
    this.columnName = null;
  }

  public RelationIdentifier getRelationIdentifier() {
    return this.relationIdentifier;
  }

  public ParentColumnTableRelation setRelationIdentifier(RelationIdentifier relationIdentifier) {
    this.relationIdentifier = relationIdentifier;
    return this;
  }

  public void unsetRelationIdentifier() {
    this.relationIdentifier = null;
  }

  /** Returns true if field relationIdentifier is set (has been assigned a value) and false otherwise */
  public boolean isSetRelationIdentifier() {
    return this.relationIdentifier != null;
  }

  public void setRelationIdentifierIsSet(boolean value) {
    if (!value) {
      this.relationIdentifier = null;
    }
  }

  public String getColumnId() {
    return this.columnId;
  }

  public ParentColumnTableRelation setColumnId(String columnId) {
    this.columnId = columnId;
    return this;
  }

  public void unsetColumnId() {
    this.columnId = null;
  }

  /** Returns true if field columnId is set (has been assigned a value) and false otherwise */
  public boolean isSetColumnId() {
    return this.columnId != null;
  }

  public void setColumnIdIsSet(boolean value) {
    if (!value) {
      this.columnId = null;
    }
  }

  public String getColumnName() {
    return this.columnName;
  }

  public ParentColumnTableRelation setColumnName(String columnName) {
    this.columnName = columnName;
    return this;
  }

  public void unsetColumnName() {
    this.columnName = null;
  }

  /** Returns true if field columnName is set (has been assigned a value) and false otherwise */
  public boolean isSetColumnName() {
    return this.columnName != null;
  }

  public void setColumnNameIsSet(boolean value) {
    if (!value) {
      this.columnName = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RELATION_IDENTIFIER:
      if (value == null) {
        unsetRelationIdentifier();
      } else {
        setRelationIdentifier((RelationIdentifier)value);
      }
      break;

    case COLUMN_ID:
      if (value == null) {
        unsetColumnId();
      } else {
        setColumnId((String)value);
      }
      break;

    case COLUMN_NAME:
      if (value == null) {
        unsetColumnName();
      } else {
        setColumnName((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RELATION_IDENTIFIER:
      return getRelationIdentifier();

    case COLUMN_ID:
      return getColumnId();

    case COLUMN_NAME:
      return getColumnName();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RELATION_IDENTIFIER:
      return isSetRelationIdentifier();
    case COLUMN_ID:
      return isSetColumnId();
    case COLUMN_NAME:
      return isSetColumnName();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ParentColumnTableRelation)
      return this.equals((ParentColumnTableRelation)that);
    return false;
  }

  public boolean equals(ParentColumnTableRelation that) {
    if (that == null)
      return false;

    boolean this_present_relationIdentifier = true && this.isSetRelationIdentifier();
    boolean that_present_relationIdentifier = true && that.isSetRelationIdentifier();
    if (this_present_relationIdentifier || that_present_relationIdentifier) {
      if (!(this_present_relationIdentifier && that_present_relationIdentifier))
        return false;
      if (!this.relationIdentifier.equals(that.relationIdentifier))
        return false;
    }

    boolean this_present_columnId = true && this.isSetColumnId();
    boolean that_present_columnId = true && that.isSetColumnId();
    if (this_present_columnId || that_present_columnId) {
      if (!(this_present_columnId && that_present_columnId))
        return false;
      if (!this.columnId.equals(that.columnId))
        return false;
    }

    boolean this_present_columnName = true && this.isSetColumnName();
    boolean that_present_columnName = true && that.isSetColumnName();
    if (this_present_columnName || that_present_columnName) {
      if (!(this_present_columnName && that_present_columnName))
        return false;
      if (!this.columnName.equals(that.columnName))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_relationIdentifier = true && (isSetRelationIdentifier());
    list.add(present_relationIdentifier);
    if (present_relationIdentifier)
      list.add(relationIdentifier);

    boolean present_columnId = true && (isSetColumnId());
    list.add(present_columnId);
    if (present_columnId)
      list.add(columnId);

    boolean present_columnName = true && (isSetColumnName());
    list.add(present_columnName);
    if (present_columnName)
      list.add(columnName);

    return list.hashCode();
  }

  @Override
  public int compareTo(ParentColumnTableRelation other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetRelationIdentifier()).compareTo(other.isSetRelationIdentifier());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRelationIdentifier()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.relationIdentifier, other.relationIdentifier);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetColumnId()).compareTo(other.isSetColumnId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetColumnId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.columnId, other.columnId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetColumnName()).compareTo(other.isSetColumnName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetColumnName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.columnName, other.columnName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ParentColumnTableRelation(");
    boolean first = true;

    sb.append("relationIdentifier:");
    if (this.relationIdentifier == null) {
      sb.append("null");
    } else {
      sb.append(this.relationIdentifier);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("columnId:");
    if (this.columnId == null) {
      sb.append("null");
    } else {
      sb.append(this.columnId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("columnName:");
    if (this.columnName == null) {
      sb.append("null");
    } else {
      sb.append(this.columnName);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (relationIdentifier == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'relationIdentifier' was not present! Struct: " + toString());
    }
    if (columnId == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'columnId' was not present! Struct: " + toString());
    }
    if (columnName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'columnName' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (relationIdentifier != null) {
      relationIdentifier.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ParentColumnTableRelationStandardSchemeFactory implements SchemeFactory {
    public ParentColumnTableRelationStandardScheme getScheme() {
      return new ParentColumnTableRelationStandardScheme();
    }
  }

  private static class ParentColumnTableRelationStandardScheme extends StandardScheme<ParentColumnTableRelation> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ParentColumnTableRelation struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RELATION_IDENTIFIER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.relationIdentifier = new RelationIdentifier();
              struct.relationIdentifier.read(iprot);
              struct.setRelationIdentifierIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // COLUMN_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.columnId = iprot.readString();
              struct.setColumnIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // COLUMN_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.columnName = iprot.readString();
              struct.setColumnNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ParentColumnTableRelation struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.relationIdentifier != null) {
        oprot.writeFieldBegin(RELATION_IDENTIFIER_FIELD_DESC);
        struct.relationIdentifier.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.columnId != null) {
        oprot.writeFieldBegin(COLUMN_ID_FIELD_DESC);
        oprot.writeString(struct.columnId);
        oprot.writeFieldEnd();
      }
      if (struct.columnName != null) {
        oprot.writeFieldBegin(COLUMN_NAME_FIELD_DESC);
        oprot.writeString(struct.columnName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ParentColumnTableRelationTupleSchemeFactory implements SchemeFactory {
    public ParentColumnTableRelationTupleScheme getScheme() {
      return new ParentColumnTableRelationTupleScheme();
    }
  }

  private static class ParentColumnTableRelationTupleScheme extends TupleScheme<ParentColumnTableRelation> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ParentColumnTableRelation struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      struct.relationIdentifier.write(oprot);
      oprot.writeString(struct.columnId);
      oprot.writeString(struct.columnName);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ParentColumnTableRelation struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.relationIdentifier = new RelationIdentifier();
      struct.relationIdentifier.read(iprot);
      struct.setRelationIdentifierIsSet(true);
      struct.columnId = iprot.readString();
      struct.setColumnIdIsSet(true);
      struct.columnName = iprot.readString();
      struct.setColumnNameIsSet(true);
    }
  }

}

